name: testCI
on:
  push:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: verify code
      run: |
        ls -la
        cat file1.txt
  
